Algoritmo "circulo"

Var

   raio, area : real


Inicio

      escreva("Digite o valor do raio circulo: ")
      leia(raio)

      area <- Pi * Exp (raio,2)

      escreva("Area =",area:7:3)


Fimalgoritmo

Fazer um programa para ler o valor "r" do raio de um círculo, e depois mostrar o valor da área do
círculo com três casas decimais. A fórmula da área do círculo é a seguinte: 𝑎𝑟𝑒𝑎 = 𝜋. 𝑟ଶ. Você pode
usar o valor de 𝜋 fornecido pela biblioteca da sua linguagem de programação, ou então, se preferir, use
diretamente o valor 3.14159.
